[package]
name = "flux_lang"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
lalrpop-util = { version = "0.19", features = ["lexer"] }
petgraph = "0.6"
once_cell = "1.19"

[build-dependencies]
lalrpop = "0.19"

[dev-dependencies]
quickcheck = "1.0"
