[package]
name = "flux_lang"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1.0"
lalrpop-util = { version = "0.22", features = ["lexer"] }
petgraph = "0.8"
once_cell = "1.21"

[build-dependencies]
lalrpop = "0.22"

[dev-dependencies]
quickcheck = "1.0"
